# Generated by Django 2.0.1 on 2019-02-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20190213_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_inicio', models.DateField()),
                ('p_fim', models.DateField()),
            ],
        ),
    ]
