# Generated by Django 2.0.1 on 2019-05-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_remove_venda_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
