# Generated by Django 2.0.1 on 2019-05-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20190526_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
