# Generated by Django 2.0.1 on 2019-06-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_delete_periodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'deletar clientes'),)},
        ),
    ]
