# Generated by Django 2.0.1 on 2019-06-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20190529_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parâmetro NF-e'), ('permissao_exemplo2', 'Permissão 2 super permission'), ('permissao_exemplo3', 'Permissão 3 super super super Goku'))},
        ),
    ]
