# Generated by Django 2.0.1 on 2019-06-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20190616_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parâmetro NF-e'), ('ver_dashboard', 'Pode visualizar o Dashboard'), ('permissao_exemplo3', 'Permissão 3 super super super Goku'))},
        ),
    ]
