# Generated by Django 2.0.1 on 2019-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, null=True)),
                ('p_inicio', models.DateField()),
                ('p_fim', models.DateField()),
            ],
        ),
    ]
